Imports System.Text.RegularExpressions

Public Class DevanagariPaliScript
    Inherits UnicodePaliScript

    Protected Overrides ReadOnly Property Halant() As String
        Get
            Return ChrWH("094D")
        End Get
    End Property

    Protected Overrides ReadOnly Property Anusvara() As String
        Get
            Return ChrWH("0902")
        End Get
    End Property

    Public Overrides ReadOnly Property MySymbolOrder() As PaliScript.SymbolOrder
        Get
            Return SymbolOrder.IndicSource
        End Get
    End Property

    Public Overrides ReadOnly Property Name() As String
        Get
            Return "Devanagari"
        End Get
    End Property

    Protected Overrides Sub PopulateSymbols()
        With VowelSigns
            .Add("ा") 'ā
            .Add("ि") 'i
            .Add("ी") 'ī
            .Add("ु") 'u
            .Add("ू") 'ū
            .Add("े") 'e
            .Add("ो") 'o
        End With
        'Populate consonants with two roman consonants
        With DiConsonants
            .Add("ख") 'kha
            .Add("घ") 'gha
            .Add("छ") 'cha
            .Add("झ") 'jha
            .Add("ठ") 'ṭha
            .Add("ढ") 'ḍha
            .Add("थ") 'tha
            .Add("ध") 'dha
            .Add("फ") 'pha
            .Add("भ") 'bha
        End With
        'Populate consonants with one roman consonant
        With MonoConsonants
            .Add("क") 'ka
            .Add("ग") 'ga
            .Add("ङ") 'ṅa
            .Add("च") 'ca
            .Add("ज") 'ja
            .Add("ञ") 'ña
            .Add("ट") 'ṭa
            .Add("ड") 'ḍa
            .Add("ण") 'ṇa
            .Add("त") 'ta
            .Add("द") 'da
            .Add("न") 'na
            .Add("प") 'pa
            .Add("ब") 'ba
            .Add("म") 'ma
            .Add("य") 'ya
            .Add("र") 'ra
            .Add("ल") 'la
            .Add("व") 'va
            .Add("स") 'sa
            .Add("ह") 'ha
            .Add("ळ") 'ḷa
        End With
        With Vowels
            'This goes before a so it will get converted first
            .Add("आ") 'ā 
            .Add("अ") 'a
            .Add("इ") 'i
            .Add("ई") 'ī
            .Add("उ") 'u
            .Add("ऊ") 'ū
            .Add("ए") 'e
            .Add("ओ") 'o
        End With
        With Irregulars
            .Add(Me.Anusvara)
        End With
        With Digits
            .Add("०") '0
            .Add("१") '1
            .Add("२") '2
            .Add("३") '3 
            .Add("४") '4
            .Add("५") '5
            .Add("६") '6
            .Add("७") '7
            .Add("८") '8
            .Add("९") '9
        End With
        PopulateAutogeneratedLists()
        BuildSymbolsList()
    End Sub

    Public Overrides Function IsUsedIn(ByVal inString As String) As Boolean
        Return Regex.IsMatch(inString, "\p{IsDevanagari}")
    End Function
End Class
