Imports System.Text.RegularExpressions

Public Class RomanPaliScript
    Inherits PaliScript

    Protected Overrides ReadOnly Property Anusvara() As String
        Get
            Return "ṃ"
        End Get
    End Property
    Public Overrides ReadOnly Property Name() As String
        Get
            Return "Roman (IAST)"
        End Get
    End Property

    Protected Overrides Sub PopulateSymbols()
        With VowelSigns
            .Add("ā") 'ā
            .Add("i") 'i
            .Add("ī") 'ī
            .Add("u") 'u
            .Add("ū") 'ū
            .Add("e") 'e
            .Add("o") 'o
        End With
        'Populate consonants with two roman consonants
        With DiConsonants
            .Add("kha") 'kha
            .Add("gha") 'gha
            .Add("cha") 'cha
            .Add("jha") 'jha
            .Add("ṭha") 'ṭha
            .Add("ḍha") 'ḍha
            .Add("tha") 'tha
            .Add("dha") 'dha
            .Add("pha") 'pha
            .Add("bha") 'bha
        End With
        'Populate consonants with one roman consonant
        With MonoConsonants
            .Add("ka") 'ka
            .Add("ga") 'ga
            .Add("ṅa") 'ṅa
            .Add("ca") 'ca
            .Add("ja") 'ja
            .Add("ña") 'ña
            .Add("ṭa") 'ṭa
            .Add("ḍa") 'ḍa
            .Add("ṇa") 'ṇa
            .Add("ta") 'ta
            .Add("da") 'da
            .Add("na") 'na
            .Add("pa") 'pa
            .Add("ba") 'ba
            .Add("ma") 'ma
            .Add("ya") 'ya
            .Add("ra") 'ra
            .Add("la") 'la
            .Add("va") 'va
            .Add("sa") 'sa
            .Add("ha") 'ha
            .Add("ḷa") 'ḷa
        End With
        With Vowels
            'This goes before a so it will get converted first in Khmer script
            .Add("ā")
            .Add("a")
            .Add("i")
            .Add("ī")
            .Add("u")
            .Add("ū")
            .Add("e")
            .Add("o")
            '.Add("ai")
            '.Add("au")
        End With
        With Irregulars
            .Add(Me.Anusvara)
        End With
        With Digits
            .Add("0") '0
            .Add("1") '1
            .Add("2") '2
            .Add("3") '3 
            .Add("4") '4
            .Add("5") '5
            .Add("6") '6
            .Add("7") '7
            .Add("8") '8
            .Add("9") '9
        End With
        PopulateAutogeneratedLists()
        BuildSymbolsList()
    End Sub

    Protected Overrides Function ApplyVowelSupression(ByVal symbol As String) As String
        Return symbol.Replace("a", "")
    End Function

    Public Overrides ReadOnly Property MySymbolOrder() As PaliScript.SymbolOrder
        Get
            Return SymbolOrder.RomanSource
        End Get
    End Property

    Protected Overrides Function ApplyAnusvara(ByVal inSymbol As String) As String
        Return inSymbol & Anusvara
    End Function

    Protected Overrides Function PopulateMatras(ByVal inConsonants As List(Of String)) As List(Of String)
        Dim matras As New List(Of String)
        For Each consonant As String In inConsonants
            For Each vowelSign As String In VowelSigns
                consonant = consonant.Replace("a", "")
                matras.Add(consonant & vowelSign)
            Next
        Next
        Return matras
    End Function

    Public Overrides Function IsUsedIn(ByVal inString As String) As Boolean
        Return Regex.IsMatch(inString, "[a-zA-ZāṭñūīḷśṅḍṣāṇṃĀṬŚṬÑŪĪĀṢḌṄŚḶṂṆḤ0-9]")
    End Function
End Class
